name: Build, Push to GHCR, and Deploy to LKE

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write # for GHCR

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # GHCR Login
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Extract current tag
      - name: Extract Current TAG
        id: extract-tag
        run: |
          CURRENT_TAG=$(grep -oP "ghcr.io/${{ github.repository_owner }}/website:\K\d+" ./k8s/deployment.yaml)
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

      # Login to GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build image
      - name: Build Docker Image
        run: |
          NEW_TAG=$(date +%Y%m%d%H%M%S)
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          docker build -t ghcr.io/${{ github.repository_owner }}/website:${NEW_TAG} .

      # Push image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/website:${{ env.NEW_TAG }}

      # Replace TAG in deployment YAML
      - name: Replace TAG in Deployment YAML
        run: |
          sed -i "s|ghcr.io/${{ github.repository_owner }}/website:${{ env.CURRENT_TAG }}|ghcr.io/${{ github.repository_owner }}/website:${{ env.NEW_TAG }}|g" ./k8s/deployment.yaml

      # Commit updated deployment
      - name: Commit Updated Deployment YAML
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update deployment tag to ${{ env.NEW_TAG }}" || echo "No changes to commit"
          git push

      # Setup kubectl
      - name: Setup kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.LINODE_KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      # Apply Kubernetes changes to LKE
      - name: Deploy to LKE
        run: |
          kubectl config set-credentials github-deployer --token=${{ secrets.GH_REPO }}
          kubectl config set-context --current --user=github-deployer
#          kubectl -n default create token github-deployer
          kubectl apply -f ./k8s/deployment.yaml










